---
- name: MOTD
  hosts: all
  vars:
    motd_ascii_art: "    _   ___  ___ _____ ___ ___  
   /_\ | _ \/ __|_   _|_ _/ _ \ 
  / _ \|   / (__  | |  | | (_) |
 /_/ \_\_|_\\___| |_| |___\__\_\
                                "
  roles:
    - jtyr.motd
