---
- name: MOTD
  hosts: all
  pre_tasks:
    - name: Install SELinux
      yum: pkg=libselinux-python state=latest
  vars:
    motd_ascii_art: "      _       _______      ______  _________  _____   ___      
     / \     |_   __ \   .' ___  ||  _   _  ||_   _|.'   `.    
    / _ \      | |__) | / .'   \_||_/ | | \_|  | | /  .-.  \   
   / ___ \     |  __ /  | |           | |      | | | |   | |   
 _/ /   \ \_  _| |  \ \_\ `.___.'\   _| |_    _| |_\  `-'  \_  
|____| |____||____| |___|`.____ .'  |_____|  |_____|`.___.\__| 
                                                               "
  roles:
    - jtyr.motd
